exports.LOGIN_TYPE = {
  MOBILENO: 1,
  GOOGLE: 2,
  QUICK: 3,
};

exports.MESSAGE_TYPE = {
  MESSAGE: 1,
  IMAGE: 2,
  AUDIO: 3,
};

exports.GIFTTYPE_TYPE = {
  IMAGE: 1,
  GIF: 2,
  SVGA: 3,
};

exports.DOCUMENT_TYPE = {
  PASSPORT: 1,
  AADHARCARD: 2,
};

exports.HISTORY_TYPE = {
  GIFT: 1, //during live received gift OR particular video's received gift
  COINPLANPURCHASE: 2,
  WITHDRAWAL: 3,
  RANDOMCALL: 4,
  LOGINBONUS: 5,
};

exports.STATUS_OF_COMPLAINT = {
  PENDING: 1,
  SOLVED: 2,
};

exports.WITHDRAWAL_STATUS = {
  DEFAULT: 0,
  PENDING: 1,
  ACCEPTED: 2,
  DECLINED: 3,
};

exports.TYPE_OF_REPORT = {
  VIDEO: 1,
  POST: 2,
  USERTOUSER: 3,
};

exports.STATUS_OF_REPORT = {
  PENDING: 1,
  SOLVED: 2,
};

exports.STATUS_OF_MESSAGE_REQUEST_TOPIC = {
  PENDING: 1,
  ACCEPTED: 2,
  REJECTED: 3,
};

exports.REPORT_TYPE = {
  I_JUST_DOES_NOT_LIKE_IT: 1,
  IT_IS_SPAM: 2,
  NUDITY_OR_SEXUAL_ACTIVITY: 3,
  HATE_SPEECH_OR_SYMBOLS: 4,
  VIOLENCE_OR_DANGEROUS_ORGANIZATION: 5,
  FALSE_INFORMATION: 6,
  BULLYING_OR_HARASSMENT: 7,
  SCAM_OR_FRAUD: 8,
  INTELLECTUAL_PROPERTY_VIOLATION: 9,
  SUICIDE_OR_SELF_INJURY: 10,
  DRUGS: 11,
  EATING_DISORDERS: 12,
  SOMETHING_ELSE: 13,
  CHILD_ABUSE: 14,
  OTHERS: 15,
};

exports.VIDEO_BANNED = {
  NUDITY_AND_ADULT_CONTENT: 1,
  HATE_AND_OFFENSIVE_SIGNS: 2,
  VIOLENCE: 3,
  GORE_AND_DISGUSTING: 4,
  WEAPONS: 5,
  SMOKING_AND_TOBACCO_PRODUCTS: 6,
  RECREATIONAL_AND_MEDICAL_DRUGS: 7,
  GAMBLING: 8,
  ALCOHOLIC_BEVERAGES: 9,
  MONEY_AND_BANKNOTES: 10,
  SELFHARM: 11,
};
