module.exports = {
  "_id": "67504261c7d0ce8e319493c3",
  "stripeSwitch": true,
  "stripePublishableKey": "pk_test_PLACEHOLDER_KEY",
  "stripeSecretKey": "YOUR_STRIPE_SECRET_KEY_HERE",
  "razorPaySwitch": true,
  "razorPayId": "YOUR_RAZORPAY_KEY_ID_HERE",
  "razorSecretKey": "YOUR_RAZORPAY_SECRET_KEY_HERE",
  "privacyPolicyLink": "https://www.termsfeed.com/live/d0e1017d-7ad3-439d-815a-bf4d195f6d0d",
  "termsOfUsePolicyLink": "https://www.termsfeed.com/live/d0e1017d-7ad3-439d-815a-bf4d195f6d0d",
  "zegoAppId": "1944303099",
  "zegoAppSignIn": "YOUR_ZEGO_APP_SIGN_IN_HERE",
  "paymentGateway": [],
  "isFakeData": true,
  "durationOfShorts": 500,
  "minCoinForCashOut": 25,
  "minWithdrawalRequestedCoin": 10,
  "createdAt": "2024-06-17T10:09:49.380Z",
  "updatedAt": "2024-09-26T10:09:57.628Z",
  "currency": {
    "name": "INR",
    "symbol": "₹",
    "countryCode": "IN",
    "currencyCode": "INR",
    "isDefault": true
  },
  "privateKey": {
    "type": "service_account",
    "project_id": "your-project-id",
    "private_key_id": "placeholder_private_key_id",
    "private_key": "",
    "client_email": "firebase-adminsdk-placeholder@your-project-id.iam.gserviceaccount.com",
    "client_id": "000000000000000000000",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-placeholder%40your-project-id.iam.gserviceaccount.com",
    "universe_domain": "googleapis.com"
  },
  "videoBanned": [
    "1"
  ],
  "googlePlaySwitch": true,
  "androidLicenseKey": "androidLicenseKey",
  "iosLicenseKey": "iosLicenseKey",
  "sightengineSecret": "sightengineSecret",
  "sightengineUser": "sightengineUser",
  "loginBonus": 5000,
  "flutterWaveId": "FLWPUBK_TEST-cdc51a4df113a91fe33a914eaf8d1c75-X",
  "flutterWaveSwitch": true,
  "isEffectActive": true,
  "isWatermarkOn": false,
  "watermarkIcon": "",
  "watermarkType": 2
};